pipeline {
    agent {
        docker {
            image 'maven:3.8.4-jdk-11'
        }
    }
    stages {
        stage('Build and Install') {
            steps {
                script {
                    sh 'mvn clean install'
                }
            }
        }
    }
    post {
        success {
            echo 'Build and install successful!'
        }
        failure {
            echo 'Build and install failed!'
        }
    }
}
