pipeline {
    agent {
        docker {
            image 'maven:3.8.4-jdk-11' // Use an official Maven image with Java 11
        }
    }
    stages {
        stage('Build and Install') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
    post {
        success {
            echo 'Build and install successful!'
        }
        failure {
            echo 'Build and install failed!'
        }
    }
}

